use eqsupply;

insert into quote_generator_manufacturer (name, address, city, country, phone, email, website) values ("Elcometer", "2, Surrey Way", "West Ham", "England", "44778938390", "sales@elcometer.com", "http://www.elcometer.com");

INSERT INTO `quote_generator_category` VALUES (1,'Abrasion Testers','A range of instruments designed for wear resistance tests'),(2,'Adhesion','A range of instruments to quantify the strength of the bond between substrate and coating, or between different coating layers or the cohesive strength of some substrates');

INSERT INTO `quote_generator_product` VALUES (1,'Elcometer 1730 Car Wash Simulator','The car wash simulator by Elcometer is used to characterise the resistance of coatings against the action of automatic car washes. Meeting the exacting specifications of Peugeot-Citroën, the Elcometer 1730 is the ideal product for determining the resistance of automotive coatings to the abrasion caused by either the brush fibres or dirty water.','Elcometer 1730',1,'1730.htm','1730.htm'),(2,'Elcometer 1720 Abrasion Testers & Washability Testers','These robust, reliable and extremely versatile machines have been designed for testing the abrasion, washability, brushability and resistance of a wide range of materials including paint, lacquers, inks, coatings, leather, wood, plastics, printed material, fabrics, etc.','Elcometer 1720',1,'1720.htm','1720.htm'),(3,'Elcometer 1720 Spongeability & Washability Testers','This version of the Elcometer 1720 is adapted for testing the spongeability and washability of paper wall coverings in accordance with EN 233 & EN 12956 Standards.','Elcometer 1720',1,'1720_5.htm','1720.htm'),(4,'Elcometer 1540 Cross Cut Tester','Simple instrument for quickly determining the adhesion of a large variety of paints. Made from special steel, it has 11 tapered teeth with 1mm spacing. Two series of lines are cut at right angles to obtain a pattern of 100 squares.','Elcometer 1540',1,'1540.htm','1540.htm');

INSERT INTO `quote_generator_product_categories` VALUES (1,1,1),(2,2,1),(3,3,1),(4,4,2);
